name: first workflow
on:
  # workflow_dispatch:
  #   inputs:
  #     versionName:
  #       required: true
  #       description: "this is version name of github workflow"
    # repository_dispatch:
    #   types: [test]
  push
  
      branches:
          - "main"
  
jobs:
    first-workflow-job:
        name: first job
        
        runs-on: ubuntu-latest
        # container:
        #   image: node:14.16
        steps:
            - name: check node version
              run: node -v
            - name: before checkout actions 
              if: github.ref == 'refs/head/main'
              run:  ls
              shell: bash

            - name: checkout steps
              uses: actions/checkout@v3 
              
            - name: after checkout action
              if: github.event.inputs.versionName == 'test'
              run:  ls
              shell: bash   
